kmz6/2025_SE_6

frontend/package-lock.json, frontend/src/App.jsx, frontend/src/pages/LectureRoomPage.css, frontend/src/pages/LectureRoomPage.jsx
=> LectureHomePage 구현

frontend/src/App.jsx, frontend/src/components/UserTableRows.jsx, frontend/src/mocks/userData.js, frontend/src/pages/MyPage.jsx, frontend/src/pages/MyPage.style.js
=> feat: 마이페이지 레이아웃 구현

frontend/src/App.jsx, frontend/src/pages/TimetablePage.jsx
=> feat: TimetablePage

frontend/src/components/Navbar.jsx, frontend/src/components/Sidebar.jsx
=> feat: NavbarSidebar

frontend/src/components/Sidebar.jsx
=> feat: 웹메일, 중앙도서관 연결 구현

frontend/src/App.jsx, frontend/src/components/Attendance/AttendanceDetail.jsx, frontend/src/components/Attendance/ProfAttend.jsx, frontend/src/components/Attendance/StudAttend.jsx, frontend/src/context/UserContext.jsx, frontend/src/pages/AttendancePage.jsx, frontend/src/pages/ProfAttendPage.jsx, frontend/src/pages/ProfLectureList.jsx, frontend/src/pages/StudAttendPage.jsx, frontend/src/pages/StudLectureList.jsx
학생 출석 페이지 레이아웃 구현
- attendance/student 수강 중인 과목 목록 확인
- attendacne/student/lectureId 해당 과목 출석 현황 확인
교수 출석 페이지 레이아웃 구현
- attendance/professor 강의 중인 과목 목록 확인
- attendance/student/lectureId 해당 과목 출석 체크 가능
+ 추가 예정
=> feat: AttendancePage

frontend/src/components/Navbar.jsx, frontend/src/context/UserContext.jsx, frontend/src/pages/LoginPage.jsx
로그인 로그아웃 구현
- console에서 로그인/로그아웃 확인할 수 있도록 함
- home으로 navigate되도록 수정
=> feat: LoginLogout

frontend/src/App.jsx, frontend/src/pages/LeaveRequest.style.js, frontend/src/pages/LeaveRequestPage.jsx
=> feat: 휴복학 신청 페이지 레이아웃 구현

frontend/src/App.jsx, frontend/src/mocks/leaveData.js, frontend/src/pages/LeaveApproval.style.js, frontend/src/pages/LeaveApprovalPage.jsx
=> feat: 휴복학 승인 페이지 레이아웃 구현

frontend/src/App.jsx
로그인 화면과 회원가입 화면에서 냅바 사이드바 안 보이도록 수정
=> feat: HideNavSidebar

frontend/src/App.jsx, frontend/src/components/Board/BoardHeader.css, frontend/src/components/Board/BoardHeader.jsx, frontend/src/components/Board/BoardListTable.css, frontend/src/components/Board/BoardListTable.jsx, frontend/src/components/Post/CommentBox.css, frontend/src/components/Post/CommentBox.jsx, frontend/src/components/Post/PostBox.css, frontend/src/components/Post/PostBox.jsx, frontend/src/components/Post/PostHeader.css, frontend/src/components/Post/PostHeader.jsx, frontend/src/pages/ArchivesListPage.css, frontend/src/pages/ArchivesListPage.jsx, frontend/src/pages/NoticePostPage.css, frontend/src/pages/NoticePostPage.jsx
- 강의자료실 리스트 구현
- 게시글 목록&게시글 화면 모듈화함
=> ArchivesListPage 구현&모듈화

frontend/src/App.jsx, frontend/src/components/GradeInput/ProfGrade.jsx, frontend/src/components/GradeInput/ProfGrade.style.js, frontend/src/pages/GradeInput.style.js, frontend/src/pages/GradeInputPage.jsx
=> Feat: GradeInputPage 구현

frontend/src/App.jsx, frontend/src/components/Syllabus/SyllabusFilterForm.jsx, frontend/src/components/Syllabus/SyllabusForm.jsx, frontend/src/components/Syllabus/SyllabusResultTable.jsx, frontend/src/pages/ProfSyllabusListPage.jsx, frontend/src/pages/ProfSyllabusPage.jsx, frontend/src/pages/StudSyllabusPage.jsx, frontend/src/pages/StudSyllabusSearchPage.jsx
강의 계획서 구현
- 학생 / 교수 분리
- 학생인 경우, 강의 계획서 검색 / 필터링 / 조회 가능
- 교수인 경우, 본인의 강의 목록 확인 / 작성 가능
=> feat: Syllabus

frontend/src/App.jsx, frontend/src/components/Post/PostBox.css, frontend/src/components/Post/PostBox.jsx, frontend/src/pages/NoticeWritePage.css, frontend/src/pages/NoticeWritePage.jsx
=> NoticeWritePage 구현

frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/mocks/assignmentData.js, frontend/src/pages/DashboardPage.jsx, frontend/src/pages/DashboardPage.style.js
=> feat: DashboardPage 구현

frontend/src/App.jsx, frontend/src/mocks/gradeData.js, frontend/src/pages/StudRankPage.jsx, frontend/src/pages/StudRankPage.style.js
=> feat:student grade page

frontend/src/components/Navbar.jsx, frontend/src/components/Sidebar.jsx, frontend/src/components/menuRoutes.js, frontend/src/layout/root-layout.jsx
냅바
- home navigate 추가
- 크기 고정
사이드바
- user_type에 따라 분기
- navigate 추가
=> feat: NavbarSidebar 기능 추가

frontend/src/App.jsx, frontend/src/components/Navbar.jsx, frontend/src/components/ProtectedRoute.jsx, frontend/src/components/menuRoutes.js, frontend/src/context/UserContext.jsx
user_type 별로 접근 가능한 페이지 지정
+ 로그인 로그아웃 관리
=> feat: ProtectedRoute

frontend/src/App.jsx, frontend/src/pages/AssignSubmitListPage.css, frontend/src/pages/AssignSubmitListPage.jsx, frontend/src/pages/AssignSubmittedDetailPage.css, frontend/src/pages/AssignSubmittedDetailPage.jsx
교수자용 과제 확인 페이지 구현
- 수강생 과제 제출 현황 리스트 페이지
- 제출한 학생 누르면 과제 내용 페이지로 이동
=> 교수자용 과제 확인 페이지 구현

frontend/src/App.jsx, frontend/src/layout/root-layout.jsx, frontend/src/pages/LoginPage.jsx
=> feat: LoginRouting

frontend/src/components/Syllabus/SyllabusFilterForm.jsx, frontend/src/components/Syllabus/SyllabusResultTable.jsx, frontend/src/pages/student/StudSyllabusSearchPage.jsx
=> fix: 강의계획서 조회 수정

frontend/src/pages/student/AssignPostPage.css, frontend/src/pages/student/LectureRoomPage.css, frontend/src/pages/student/LectureRoomPage.jsx, frontend/src/pages/studfac/ArchivesListPage.css, frontend/src/pages/studfac/ArchivesPostPage.css, frontend/src/pages/studfac/AssignListPage.css, frontend/src/pages/studfac/AssignSubmittedDetailPage.css, frontend/src/pages/studfac/NoticeListPage.css, frontend/src/pages/studfac/NoticeListPage.jsx, frontend/src/pages/studfac/NoticePostPage.css
- notice, archive, assignment레이아웃 마진 테두리 통일
- 공지사항 내 검색 기능 구현
=> 레이아웃 통일(마진 테두리)&공지사항 검색 구현

frontend/src/components/Syllabus/SyllabusFilterForm.jsx, frontend/src/components/Syllabus/SyllabusResultTable.jsx, frontend/src/pages/faculty/ProfSyllabusListPage.jsx, frontend/src/pages/student/StudSyllabusPage.jsx, frontend/src/pages/student/StudSyllabusSearchPage.jsx, frontend/src/styles/Syllabus.style.js
학생용 강의 계획서 페이지 라우팅 수정
style.js 사용 (레이아웃 수정)
=> feat: Syllabus 수정

frontend/src/pages/student/DashboardPage.jsx, frontend/src/styles/DashboardPage.style.js
=> style: 스타일 하이라이트 변경

frontend/src/pages/SignupPage.jsx
회원가입 페이지
비밀번호 입력, 비밀번호 확인 기능 추가
폼 입력 시 유효성 검증 추가
=> fix: SignupPage

backend/app.js, backend/controllers/signupController.js, backend/models/authModel.js, backend/models/signupModel.js, backend/routes/signup.js, frontend/src/apis/signup/signup.js, frontend/src/components/Navbar.jsx, frontend/src/pages/SignupPage.jsx
회원가입 / 로그인 API 연결
내비게이션 바에서 사용자 이름 뜨도록 authModel.js 수정
=> feat: 회원가입 / 로그인 API 연결

backend/app.js, backend/controllers/resetpwdController.js, backend/models/authModel.js, backend/models/resetpwdModel.js, backend/routes/resetpwd.js, frontend/src/apis/resetpwd/resetpwd.js, frontend/src/pages/studfac/ResetPasswdPage.jsx
비밀번호 초기화 기능 API 연결
스태프 로그인 시 staff_tb에 연결
=> feat: ResetPasswd API 연결

backend/app.js, backend/controllers/student/sugangController.js, backend/models/student/sugangModel.js, backend/routes/student/sugang.js, frontend/src/apis/sugang/sugang.js, frontend/src/pages/student/SugangPage.jsx, frontend/src/styles/SugangPage.style.js
API 연동
과목 조회
신청한 과목 조회
수강신청
수강삭제
기능 추가
로컬스토리지 사용한 즐겨찾기 기능
신청 학점 확인 기능
=> feat: 수강신청 페이지 API 연동

backend/models/student/timetableModel.js, frontend/src/components/Navbar.jsx, frontend/src/components/ProtectedRoute.jsx, frontend/src/components/Syllabus/SyllabusFilterForm.jsx, frontend/src/components/Timetable.jsx, frontend/src/context/UserContext.jsx, frontend/src/layout/root-layout.jsx, frontend/src/pages/HomePage.jsx, frontend/src/pages/faculty/ProfSyllabusListPage.jsx, frontend/src/pages/faculty/ProfSyllabusPage.jsx, frontend/src/pages/student/StudSyllabusPage.jsx, frontend/src/pages/student/StudSyllabusSearchPage.jsx
시간표
- 포트 번호 하드 코딩 수정
강의 계획서
- 학기 필터링 오류 수정
=> fix: 시간표 / 강의 계획서 수정

backend/constants/gradePoints.js, backend/routes/common/material.js, backend/routes/common/notice.js, frontend/src/components/Post/PostWriteHeader.css, frontend/src/components/Post/PostWriteHeader.jsx, frontend/src/pages/faculty/ArchivesWritePage.jsx, frontend/src/pages/faculty/NoticeWritePage.jsx, frontend/src/pages/studfac/ArchivesListPage.jsx, frontend/src/pages/studfac/ArchivesPostPage.jsx, frontend/src/pages/studfac/NoticeListPage.jsx, frontend/src/pages/studfac/NoticePostPage.jsx
- Notice&Archive 학정번호 추가
- 글쓰기 페이지 헤더 수정 (컴포넌트 새로 만들어 대체함)
- 버전 문제로 인한 서버 실행 불가 -> gradePoints.js 파일 수정
=> Notice&Archive 학정번호 추가 / 글쓰기 페이지 헤더 수정

backend/routes/common/qna.js, frontend/src/App.jsx, frontend/src/components/Post/CommentBox.css, frontend/src/components/Post/CommentBox.jsx, frontend/src/pages/studfac/QnAPostPage.jsx, frontend/src/pages/studfac/QnAWritePage.jsx
=> feat: QnA게시판 댓글 api 연결 및 해결

frontend/src/pages/faculty/AssignSubmitListPage.css, frontend/src/pages/faculty/AssignSubmitListPage.jsx, frontend/src/pages/student/AssignPostPage.jsx, frontend/src/pages/studfac/AssignListPage.css, frontend/src/pages/studfac/AssignListPage.jsx, frontend/src/pages/studfac/AssignSubmittedDetailPage.jsx
=> feat: 과제페이지 레이아웃 수정 및 과제 제출률 시각화
